name: vroom_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  camera: ^0.10.1
  image: ^3.2.2
  cupertino_icons: ^1.0.2
  extended_image: ^4.1.0
  remixicon: ^1.0.0
  intl: ^0.17.0
  readmore: ^2.1.0
  flutter_svg: ^1.1.6
  linkwell: ^2.0.6
  get_storage: 
  dio: ^4.0.0   
  async: ^2.8.1
  flutter_datetime_picker: ^1.5.1 
  image_picker: ^0.8.3+2
  flutter_inappwebview: ^5.3.2
  flutter_local_notifications: ^9.0.2
  qr_flutter: ^4.0.0
  url_launcher: ^6.0.9
  firebase_core: ^2.4.0  
  flutter_rating_bar: ^4.0.0 
  firebase_messaging: ^14.1.4
  cloud_firestore: ^4.2.0 
  flutter_notification_channel: ^2.0.0 
  firebase_database: ^10.0.9
  firebase_analytics: ^10.0.7
  flutter_easyloading: ^3.0.0
  firebase_auth: ^4.2.0
  firebase_in_app_messaging: ^0.7.0+8
  flutter_scroll_shadow: ^1.0.1
  map_launcher: ^2.1.1 
  sentry: ^6.0.1
  group_button: ^3.1.0
  lottie: any
  sensors_plus: ^1.1.0
  new_version: ^0.2.2
  flutter_shake_animated: ^0.0.5
  barcode_scan2: ^4.1.4 
  share_plus: ^2.1.4 
  pin_code_fields: ^7.3.0
  uni_links: ^0.5.1
  flutter_speed_dial: ^4.4.0 
  intl_phone_number_input: ^0.7.0+2
  flutter_map: any 
  flutter_map_location: any 
  crypto: ^3.0.1  
  slide_to_act: ^2.0.1
  horizontal_data_table: ^3.5.0
  package_info_plus: ^1.3.0
  launch_review: ^3.0.1
  carousel_slider: ^4.0.0
  flutter_animate: ^2.0.1
  flutter_paytabs_bridge: ^2.1.8
  flutter_barcode_scanner: ^2.0.0
  flutter_launcher_icons: ^0.9.2
  audioplayers: ^1.1.1
  get: 4.6.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true 
  assets:
    - assets/images/logo.png
    - assets/images/car.png
    - assets/images/acura.png
    - assets/images/user.png
    - assets/images/crown.png
    - assets/images/facebook.png
    - assets/images/google.png
    - assets/images/apple.png
    - assets/images/coins.png
    - assets/images/diamonds.png
    - assets/images/wheel.png
    - assets/images/cursor.png
    - assets/images/match.png
    - assets/sounds/

